### ISSUE TITLE
Can't load NVML library

### ISSUE THREAD

**Issue by camax** [PTRFRLL/nv-docker-trex#31]
Hi,
I'm using Unraid, I updated to the new version and got this error: 

`20211025 09:25:39 WARN: Can't load NVML library, dlopen(25): failed to load libnvidia-ml.so, libnvidia-ml.so: cannot open shared object file: No such file or directory`

How can i fix this ?

**Comment by camax** [comment]
I found my way to fix the issue, installing libnvidia-ml-dev on the container using the console tool..

`apt-get update && apt-get install libnvidia-ml-dev`

Cheers.

**Comment by PTRFRLL** [comment]
Good find! I'll get that added to the container.

**Comment by PTRFRLL** [comment]
Closed by #37
